apiVersion: v1
kind: Service
metadata:
  name: tree-selling-app-service
spec:
  selector:
    app: tree-selling-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Match the port your app listens to inside the container
  type: LoadBalancer  # Exposes the service externally. Change to NodePort or ClusterIP based on your needs

