name: Build, Test, and Deploy Tree Selling App with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ secrets.DOCKER_USERNAME }}/tree-selling-app
          tree-selling-app
        tags: |
          type=sha,format=long
          type=ref,event=branch

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Pull Docker image
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/tree-selling-app:${{ needs.build.outputs.image-tag }}

    - name: Run Docker container
      run: |
        docker run -d -p 8080:80 --name tree-test \
          ${{ secrets.DOCKER_USERNAME }}/tree-selling-app:${{ needs.build.outputs.image-tag }}

    - name: Wait for app startup
      uses: jwgmeligmeyling/wait-for-port-action@v1
      with:
        host: localhost
        port: 8080
        timeout: 20

    - name: Run accessibility test
      run: |
        curl --fail --retry 5 --retry-delay 3 http://localhost:8080 || exit 1

    - name: Cleanup containers
      if: always()
      run: |
        docker rm -f tree-test

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    environment: 
      name: production
      url: https://hub.docker.com/r/${{ secrets.DOCKER_USERNAME }}/tree-selling-app

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Promote to latest
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/tree-selling-app:${{ needs.build.outputs.image-tag }}
        docker tag ${{ secrets.DOCKER_USERNAME }}/tree-selling-app:${{ needs.build.outputs.image-tag }} \
          ${{ secrets.DOCKER_USERNAME }}/tree-selling-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/tree-selling-app:latest
