name: Build, Test, and Deploy Tree Selling App with Docker

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx (for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t tree-selling-app:latest .

  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image

    steps:
    # Step 1: Checkout repository (to access the code and Dockerfile)
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Build the Docker image (again in test step to ensure consistency)
    - name: Build Docker image for testing
      run: |
        docker build -t tree-selling-app:latest .

    # Step 4: Log in to Docker Hub using GitHub Secrets for Docker credentials
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username from GitHub Secrets
        password: ${{ secrets.DOCKER_TOKEN }}  # Docker Hub token from GitHub Secrets

    # Step 5: Run Docker container to check if app is working
    - name: Run Docker container
      run: |
        docker run -d -p 8080:80 --name tree-selling-app tree-selling-app:latest

    # Step 6: Wait for the app to start
    - name: Wait for the app to start
      run: sleep 15  # Allow time for the app to load

    # Step 7: Run a test to confirm the app is working (using curl)
    - name: Check if app is accessible
      run: |
        curl --fail http://localhost:8080 || exit 1  # Ensure the app is reachable

    # Step 8: Clean up (stop the container after testing)
    - name: Stop Docker container after testing
      run: |
        docker ps -q -f "ancestor=tree-selling-app" | xargs -r docker stop
        docker ps -q -f "ancestor=tree-selling-app" | xargs -r docker rm

  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image
    needs: [build, test]  # Ensure this step runs only after the build and test jobs complete successfully
    environment: production  # Define the environment for deployment

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username
        password: ${{ secrets.DOCKER_TOKEN }}  # Docker Hub token

    # Step 3: Tag and push the Docker image to Docker Hub
    - name: Tag and push Docker image
      run: |
        # Ensure the image is tagged correctly
        docker tag tree-selling-app:latest ${{ secrets.DOCKER_USERNAME }}/tree-selling-app:latest
        # Push the image to Docker Hub
        docker push ${{ secrets.DOCKER_USERNAME }}/tree-selling-app:latest

 
